* Configure and build the desktop, pixmaps, and po subdirectories even if   UBIQUITY_NO_GTK is set.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -928,13 +928,14 @@ PKG_CONFIG
 PYGTK_CFLAGS
 PYGTK_LIBS
 PYGTK_CODEGEN
+PYGTK_CODEGEN_TRUE
+PYGTK_CODEGEN_FALSE
 PYGTK_DEFSDIR
 GLIB_GENMARSHAL
 GTK_CFLAGS
 GTK_LIBS
 UBIQUITY_DEPENDS_CFLAGS
 UBIQUITY_DEPENDS_LIBS
-scriptsdir
 pixmapsdir
 LIBOBJS
 LTLIBOBJS'
@@ -4414,7 +4415,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4417 "configure"' > conftest.$ac_ext
+  echo '#line 4418 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7145,11 +7146,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7148: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7149: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7152: \$? = $ac_status" >&5
+   echo "$as_me:7153: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7413,11 +7414,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7416: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7417: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7420: \$? = $ac_status" >&5
+   echo "$as_me:7421: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7517,11 +7518,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7520: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7521: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7524: \$? = $ac_status" >&5
+   echo "$as_me:7525: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9814,7 +9815,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9817 "configure"
+#line 9818 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9914,7 +9915,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9917 "configure"
+#line 9918 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12250,11 +12251,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12253: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12254: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12257: \$? = $ac_status" >&5
+   echo "$as_me:12258: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12354,11 +12355,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12357: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12358: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12361: \$? = $ac_status" >&5
+   echo "$as_me:12362: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13915,11 +13916,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13918: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13919: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13922: \$? = $ac_status" >&5
+   echo "$as_me:13923: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14019,11 +14020,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14022: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14023: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14026: \$? = $ac_status" >&5
+   echo "$as_me:14027: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16206,11 +16207,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16209: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16210: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16213: \$? = $ac_status" >&5
+   echo "$as_me:16214: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16474,11 +16475,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16477: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16478: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16481: \$? = $ac_status" >&5
+   echo "$as_me:16482: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16578,11 +16579,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16581: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16582: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16585: \$? = $ac_status" >&5
+   echo "$as_me:16586: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22917,6 +22918,7 @@ rm -f conftest.err conftest.$ac_ext
 CPPFLAGS="$save_CPPFLAGS"
 
 
+if test "x$UBIQUITY_NO_GTK" = x; then
 
 
 if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
@@ -23150,7 +23152,7 @@ echo "${ECHO_T}yes" >&6; }
 fi
 
 
-# Extract the first word of "pygtk-codegen-2.0", so it can be a program name with args.
+  # Extract the first word of "pygtk-codegen-2.0", so it can be a program name with args.
 set dummy pygtk-codegen-2.0; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
@@ -23191,20 +23193,30 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-if test "x$PYGTK_CODEGEN" = xno; then
-  { { echo "$as_me:$LINENO: error: could not find pygtk-codegen-2.0 script" >&5
-echo "$as_me: error: could not find pygtk-codegen-2.0 script" >&2;}
-   { (exit 1); exit 1; }; }
+else
+
+
+  PYGTK_CODEGEN=no
+
 fi
 
-{ echo "$as_me:$LINENO: checking for pygtk defs" >&5
-echo $ECHO_N "checking for pygtk defs... $ECHO_C" >&6; }
-PYGTK_DEFSDIR=`$PKG_CONFIG --variable=defsdir pygtk-2.0`
+ if test "x$PYGTK_CODEGEN" != xno; then
+  PYGTK_CODEGEN_TRUE=
+  PYGTK_CODEGEN_FALSE='#'
+else
+  PYGTK_CODEGEN_TRUE='#'
+  PYGTK_CODEGEN_FALSE=
+fi
 
-{ echo "$as_me:$LINENO: result: $PYGTK_DEFSDIR" >&5
+if test "x$PYGTK_CODEGEN" != xno; then
+  { echo "$as_me:$LINENO: checking for pygtk defs" >&5
+echo $ECHO_N "checking for pygtk defs... $ECHO_C" >&6; }
+  PYGTK_DEFSDIR=`$PKG_CONFIG --variable=defsdir pygtk-2.0`
+
+  { echo "$as_me:$LINENO: result: $PYGTK_DEFSDIR" >&5
 echo "${ECHO_T}$PYGTK_DEFSDIR" >&6; }
 
-# Extract the first word of "glib-genmarshal", so it can be a program name with args.
+  # Extract the first word of "glib-genmarshal", so it can be a program name with args.
 set dummy glib-genmarshal; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
@@ -23245,7 +23257,7 @@ fi
 
 
 
-# Check whether --enable-gtktest was given.
+  # Check whether --enable-gtktest was given.
 if test "${enable_gtktest+set}" = set; then
   enableval=$enable_gtktest;
 else
@@ -23559,7 +23571,6 @@ rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
 
 
 
-
 pkg_failed=no
 { echo "$as_me:$LINENO: checking for UBIQUITY_DEPENDS" >&5
 echo $ECHO_N "checking for UBIQUITY_DEPENDS... $ECHO_C" >&6; }
@@ -23570,20 +23581,20 @@ if test -n "$PKG_CONFIG"; then
     else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"
-			   gtk+-2.0 >= \$GTK_REQUIRED
-			   libart-2.0
-			   \"") >&5
+	gtk+-2.0 >= \$GTK_REQUIRED
+	libart-2.0
+	\"") >&5
   ($PKG_CONFIG --exists --print-errors "
-			   gtk+-2.0 >= $GTK_REQUIRED
-			   libart-2.0
-			   ") 2>&5
+	gtk+-2.0 >= $GTK_REQUIRED
+	libart-2.0
+	") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
   pkg_cv_UBIQUITY_DEPENDS_CFLAGS=`$PKG_CONFIG --cflags "
-			   gtk+-2.0 >= $GTK_REQUIRED
-			   libart-2.0
-			   " 2>/dev/null`
+	gtk+-2.0 >= $GTK_REQUIRED
+	libart-2.0
+	" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -23597,20 +23608,20 @@ if test -n "$PKG_CONFIG"; then
     else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"
-			   gtk+-2.0 >= \$GTK_REQUIRED
-			   libart-2.0
-			   \"") >&5
+	gtk+-2.0 >= \$GTK_REQUIRED
+	libart-2.0
+	\"") >&5
   ($PKG_CONFIG --exists --print-errors "
-			   gtk+-2.0 >= $GTK_REQUIRED
-			   libart-2.0
-			   ") 2>&5
+	gtk+-2.0 >= $GTK_REQUIRED
+	libart-2.0
+	") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
   pkg_cv_UBIQUITY_DEPENDS_LIBS=`$PKG_CONFIG --libs "
-			   gtk+-2.0 >= $GTK_REQUIRED
-			   libart-2.0
-			   " 2>/dev/null`
+	gtk+-2.0 >= $GTK_REQUIRED
+	libart-2.0
+	" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -23630,22 +23641,22 @@ else
 fi
         if test $_pkg_short_errors_supported = yes; then
 	        UBIQUITY_DEPENDS_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "
-			   gtk+-2.0 >= $GTK_REQUIRED
-			   libart-2.0
-			   "`
+	gtk+-2.0 >= $GTK_REQUIRED
+	libart-2.0
+	"`
         else
 	        UBIQUITY_DEPENDS_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "
-			   gtk+-2.0 >= $GTK_REQUIRED
-			   libart-2.0
-			   "`
+	gtk+-2.0 >= $GTK_REQUIRED
+	libart-2.0
+	"`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$UBIQUITY_DEPENDS_PKG_ERRORS" >&5
 
 	{ { echo "$as_me:$LINENO: error: Package requirements (
-			   gtk+-2.0 >= $GTK_REQUIRED
-			   libart-2.0
-			   ) were not met:
+	gtk+-2.0 >= $GTK_REQUIRED
+	libart-2.0
+	) were not met:
 
 $UBIQUITY_DEPENDS_PKG_ERRORS
 
@@ -23657,9 +23668,9 @@ and UBIQUITY_DEPENDS_LIBS to avoid the need to call pkg-config.
 See the pkg-config man page for more details.
 " >&5
 echo "$as_me: error: Package requirements (
-			   gtk+-2.0 >= $GTK_REQUIRED
-			   libart-2.0
-			   ) were not met:
+	gtk+-2.0 >= $GTK_REQUIRED
+	libart-2.0
+	) were not met:
 
 $UBIQUITY_DEPENDS_PKG_ERRORS
 
@@ -23701,7 +23712,9 @@ echo "${ECHO_T}yes" >&6; }
 	:
 fi
 
+  ac_config_files="$ac_config_files src/Makefile src/cut-and-paste/Makefile src/cut-and-paste/e-map/Makefile"
 
+fi
 
 
 cat >>confdefs.h <<_ACEOF
@@ -23711,10 +23724,7 @@ _ACEOF
 pixmapsdir="${datadir}/${PACKAGE}/pixmaps"
 
 
-
-
-
-ac_config_files="$ac_config_files Makefile desktop/Makefile pixmaps/Makefile po/Makefile.in src/Makefile src/cut-and-paste/Makefile src/cut-and-paste/e-map/Makefile"
+ac_config_files="$ac_config_files Makefile desktop/Makefile pixmaps/Makefile po/Makefile.in"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -23848,6 +23858,13 @@ if test -z "${am__fastdepCC_TRUE}" && test -z "${am__fastdepCC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${PYGTK_CODEGEN_TRUE}" && test -z "${PYGTK_CODEGEN_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"PYGTK_CODEGEN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"PYGTK_CODEGEN\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -24334,13 +24351,13 @@ do
     "depfiles") CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
     "default-1") CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
     "intltool") CONFIG_COMMANDS="$CONFIG_COMMANDS intltool" ;;
+    "src/Makefile") CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
+    "src/cut-and-paste/Makefile") CONFIG_FILES="$CONFIG_FILES src/cut-and-paste/Makefile" ;;
+    "src/cut-and-paste/e-map/Makefile") CONFIG_FILES="$CONFIG_FILES src/cut-and-paste/e-map/Makefile" ;;
     "Makefile") CONFIG_FILES="$CONFIG_FILES Makefile" ;;
     "desktop/Makefile") CONFIG_FILES="$CONFIG_FILES desktop/Makefile" ;;
     "pixmaps/Makefile") CONFIG_FILES="$CONFIG_FILES pixmaps/Makefile" ;;
     "po/Makefile.in") CONFIG_FILES="$CONFIG_FILES po/Makefile.in" ;;
-    "src/Makefile") CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
-    "src/cut-and-paste/Makefile") CONFIG_FILES="$CONFIG_FILES src/cut-and-paste/Makefile" ;;
-    "src/cut-and-paste/e-map/Makefile") CONFIG_FILES="$CONFIG_FILES src/cut-and-paste/e-map/Makefile" ;;
     "po/stamp-it") CONFIG_COMMANDS="$CONFIG_COMMANDS po/stamp-it" ;;
 
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -24604,19 +24621,20 @@ PKG_CONFIG!$PKG_CONFIG$ac_delim
 PYGTK_CFLAGS!$PYGTK_CFLAGS$ac_delim
 PYGTK_LIBS!$PYGTK_LIBS$ac_delim
 PYGTK_CODEGEN!$PYGTK_CODEGEN$ac_delim
+PYGTK_CODEGEN_TRUE!$PYGTK_CODEGEN_TRUE$ac_delim
+PYGTK_CODEGEN_FALSE!$PYGTK_CODEGEN_FALSE$ac_delim
 PYGTK_DEFSDIR!$PYGTK_DEFSDIR$ac_delim
 GLIB_GENMARSHAL!$GLIB_GENMARSHAL$ac_delim
 GTK_CFLAGS!$GTK_CFLAGS$ac_delim
 GTK_LIBS!$GTK_LIBS$ac_delim
 UBIQUITY_DEPENDS_CFLAGS!$UBIQUITY_DEPENDS_CFLAGS$ac_delim
 UBIQUITY_DEPENDS_LIBS!$UBIQUITY_DEPENDS_LIBS$ac_delim
-scriptsdir!$scriptsdir$ac_delim
 pixmapsdir!$pixmapsdir$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 72; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 73; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
