Fix intltool handling; po/Makefile.in.in was still coming from gettext. Pass no-xml to IT_PROG_INTLTOOL so that we don't need to build-depend on libxml-parser-perl.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13042,6 +13042,7 @@ _ACEOF
 
 
 
+
 case "$am__api_version" in
     1.01234)
 	{ { echo "$as_me:$LINENO: error: Automake 1.5 or newer is required to use intltool" >&5
@@ -13052,19 +13053,19 @@ echo "$as_me: error: Automake 1.5 or newer is required to use intltool" >&2;}
     ;;
 esac
 
-if test -n ""; then
-    { echo "$as_me:$LINENO: checking for intltool >= " >&5
-echo $ECHO_N "checking for intltool >= ... $ECHO_C" >&6; }
+if test -n "0.40.0"; then
+    { echo "$as_me:$LINENO: checking for intltool >= 0.40.0" >&5
+echo $ECHO_N "checking for intltool >= 0.40.0... $ECHO_C" >&6; }
 
-    INTLTOOL_REQUIRED_VERSION_AS_INT=`echo  | awk -F. '{ print $ 1 * 1000 + $ 2 * 100 + $ 3; }'`
+    INTLTOOL_REQUIRED_VERSION_AS_INT=`echo 0.40.0 | awk -F. '{ print $ 1 * 1000 + $ 2 * 100 + $ 3; }'`
     INTLTOOL_APPLIED_VERSION=`intltool-update --version | head -1 | cut -d" " -f3`
     INTLTOOL_APPLIED_VERSION_AS_INT=`echo $INTLTOOL_APPLIED_VERSION | awk -F. '{ print $ 1 * 1000 + $ 2 * 100 + $ 3; }'`
 
     { echo "$as_me:$LINENO: result: $INTLTOOL_APPLIED_VERSION found" >&5
 echo "${ECHO_T}$INTLTOOL_APPLIED_VERSION found" >&6; }
     test "$INTLTOOL_APPLIED_VERSION_AS_INT" -ge "$INTLTOOL_REQUIRED_VERSION_AS_INT" ||
-	{ { echo "$as_me:$LINENO: error: Your intltool is too old.  You need intltool  or later." >&5
-echo "$as_me: error: Your intltool is too old.  You need intltool  or later." >&2;}
+	{ { echo "$as_me:$LINENO: error: Your intltool is too old.  You need intltool 0.40.0 or later." >&5
+echo "$as_me: error: Your intltool is too old.  You need intltool 0.40.0 or later." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -13355,6 +13356,47 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
+# Extract the first word of "gmsgfmt", so it can be a program name with args.
+set dummy gmsgfmt; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_GMSGFMT+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $GMSGFMT in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_GMSGFMT="$GMSGFMT" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_GMSGFMT="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_path_GMSGFMT" && ac_cv_path_GMSGFMT="$MSGFMT"
+  ;;
+esac
+fi
+GMSGFMT=$ac_cv_path_GMSGFMT
+if test -n "$GMSGFMT"; then
+  { echo "$as_me:$LINENO: result: $GMSGFMT" >&5
+echo "${ECHO_T}$GMSGFMT" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
 if test -z "$XGETTEXT" -o -z "$MSGMERGE" -o -z "$MSGFMT"; then
     { { echo "$as_me:$LINENO: error: GNU gettext tools not found; required for intltool" >&5
 echo "$as_me: error: GNU gettext tools not found; required for intltool" >&2;}
@@ -13419,7 +13461,7 @@ if test -z "`$INTLTOOL_PERL -v | fgrep '5.' 2> /dev/null`"; then
 echo "$as_me: error: perl 5.x required for intltool" >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test "x" != "xno-xml"; then
+if test "xno-xml" != "xno-xml"; then
    { echo "$as_me:$LINENO: checking for XML::Parser" >&5
 echo $ECHO_N "checking for XML::Parser... $ECHO_C" >&6; }
    if `$INTLTOOL_PERL -e "require XML::Parser" 2>/dev/null`; then
@@ -18256,17 +18298,11 @@ _LT_EOF
 	'"s|^|	$ac_top_srcdir/|" \
       "$srcdir/po/POTFILES.in" | sed '$!s/$/ \\/' >"po/POTFILES"
 
-    if test ! -f "po/Makefile"; then
-      { { echo "$as_me:$LINENO: error: po/Makefile is not ready." >&5
-echo "$as_me: error: po/Makefile is not ready." >&2;}
-   { (exit 1); exit 1; }; }
-    fi
-    mv "po/Makefile" "po/Makefile.tmp"
     sed '/^POTFILES =/,/[^\\]$/ {
 		/^POTFILES =/!d
 		r po/POTFILES
 	  }
-	 ' "po/Makefile.tmp" >"po/Makefile"
+	 ' "po/Makefile.in" >"po/Makefile"
     rm -f "po/Makefile.tmp"
     mv "po/stamp-it.tmp" "po/stamp-it"
    ;;
