partman confirm dialog displays really what will be done
partman confirmation dialog showed that an ext4 partition will be
created. However zsys-setup repartitions it to create the zfs pools. We
now catch the message and update it to display what wil actually be done
to the disk (LP: #1847719)

diff --git a/scripts/zsys-setup b/scripts/zsys-setup
--- a/scripts/zsys-setup
+++ b/scripts/zsys-setup
@@ -156,12 +156,65 @@ prepare_target() {
 	done
 }
 
+get_layout() {
+	# Returns disk, base name of the partition and partition numbers to create
+	target="$1"
+
+	# The entire disk has been formatted with use_device
+	# There is either one ext4 partition or one ext4 and one ESP
+	part="$(grep -E "\s${target}\s" /proc/mounts | awk '{print $1}')"
+
+	if [ -z "${part}" ]; then
+		echo "E: Couldn't identify partition matching ${target}. Exiting!"
+		exit 1
+	fi
+
+	disk="$(lsblk -lns -o TYPE,PATH ${part}| grep disk| awk '{print $2}')"
+
+	if [ -z "${disk}" ]; then
+		echo "E: Couldn't identify disk for partition ${part}. Exiting!"
+		exit 1
+	fi
+	# Some disks have letters in the partion number like /dev/nvme0n1p1
+	# In this case we want to retrieve 'p' so we deal only with partition number
+	# in the rest of the script and prepend the base.
+	partbase="$(echo ${part} | sed -e 's/[0-9]*$//' | sed -e "s#${disk}##")"
+
+	partgrub=$(lsblk -n -o TYPE ${disk}|grep ^part| wc -l)
+	if [ "$IS_EFI" = "true" ]; then
+		# No extended partition on EFI + GPT
+		# The layout is
+		# 1: ESP
+		# 2: grub
+		# 3: swap
+		# 4: bpool
+		# 5: rpool
+		partswap=3
+		partbpool=4
+		partrpool=5
+	else
+		# MBR pools are on extended partition
+		# The layout is:
+		# 1: grub
+		# 2: Extended
+		# 5: swap
+		# 6: bpool
+		# 7: rpool
+		partswap=5
+		partbpool=6
+		partrpool=7
+	fi
+
+	echo "OK|${disk}|${partbase}|${partgrub}|${partswap}|${partbpool}|${partrpool}"
+}
+
 format_disk() {
 	disk="$1"
-	partgrub="$2"
-	partbpool="$3"
-	partrpool="$4"
-	ss="$5"
+	partbase="$2"
+	partgrub="$3"
+	partbpool="$4"
+	partrpool="$5"
+	ss="$6"
 	partswap=$(( partbpool - 1 ))
 	partext=$(( partgrub + 1 ))
 	sfdiskopts=""
@@ -336,56 +389,50 @@ echo "I: Running $(basename "$0") ${COMMAND}"
 if [ -z "${COMMAND}" ]; then
 	echo "E: ${COMMAND} is mandatory. Exiting!"
 	exit 1
-elif [ "${COMMAND}" = "init" ]; then
-	# The entire disk has been formatted with use_device
-	# There is either one ext4 partition or one ext4 and one ESP
-	PART=$(grep -E "\s${TARGET}\s" /proc/mounts | awk '{print $1}')
+elif [ "${COMMAND}" = "layout" ]; then
+	# At this stage we don't know what partman will do so just detect if it's an UEFI system
+	IS_EFI="false"
+	if [ -d "/sys/firmware/efi" ]; then
+		IS_EFI="true"
+	fi
 
-	if [ -z "${PART}" ]; then
-		echo "E: Couldn't identify partition matching ${TARGET}. Exiting!"
+	# Just displays de layout that will be created without any change to the disk.
+	# At this stage we don't now yet the size of the partition that will be created.
+	IFS="|" read ERR DISK PARTBASE PARTGRUB PARTSWAP PARTBPOOL PARTRPOOL<<EOF
+$(get_layout ${TARGET})
+EOF
+
+	if [ "${ERR}" != "OK" ]; then
+		echo "${ERR}"
 		exit 1
 	fi
 
-	DISK="$(lsblk -lns -o TYPE,PATH ${PART}| grep disk| awk '{print $2}')"
+	cat > /tmp/$(basename $0).layout <<EOF
+disk:${DISK}
+part:ext4:grub:${DISK}${PARTBASE}${PARTGRUB}
+part:swap:swap:${DISK}${PARTBASE}${PARTSWAP}
+part:zfs:bpool:${DISK}${PARTBASE}${PARTBPOOL}
+part:zfs:rpool:${DISK}${PARTBASE}${PARTRPOOL}
+EOF
 
-	echo "I: Partition table before init of ZFS"
-	partx --show "${DISK}"
-
-	# Some disks have letters in the partion number like /dev/nvme0n1p1
-	# In this case we want to retrieve 'p' so we deal only with partition number
-	# in the rest of the script and prepend the base.
-	PARTBASE="$(echo ${PART} | sed -e 's/[0-9]*$//' | sed -e "s#${DISK}##")"
-
+elif [ "${COMMAND}" = "init" ]; then
 	# Better check if the ESP has been created than if it's a EFI system
 	IS_EFI="false"
 	if grep -q "\s${ESP}\s" /proc/mounts; then
 		IS_EFI="true"
 	fi
 
-	PARTGRUB=$(lsblk -n -o TYPE ${DISK}|grep ^part| wc -l)
-	if [ "$IS_EFI" = "true" ]; then
-		# No extended partition on EFI + GPT
-		# The layout is
-		# 1: ESP
-		# 2: grub
-		# 3: swap
-		# 4: bpool
-		# 5: rpool
-		PARTSWAP=3
-		PARTBPOOL=4
-		PARTRPOOL=5
-	else
-		# MBR pools are on extended partition
-		# The layout is:
-		# 1: grub
-		# 2: Extended
-		# 5: swap
-		# 6: bpool
-		# 7: rpool
-		PARTSWAP=5
-		PARTBPOOL=6
-		PARTRPOOL=7
+	IFS="|" read ERR DISK PARTBASE PARTGRUB PARTSWAP PARTBPOOL PARTRPOOL<<EOF
+$(get_layout ${TARGET})
+EOF
+
+	if [ "${ERR}" != "OK" ]; then
+		echo "${ERR}"
+		exit 1
 	fi
+
+	echo "I: Partition table before init of ZFS"
+	partx --show "${DISK}"
 
 	# Swap files are not supported on ZFS, we use a swap partition instead:
 	SWAPFILE="$(grep "^${TARGET}" /proc/swaps |awk '{print $1}')"
@@ -403,7 +450,7 @@ elif [ "${COMMAND}" = "init" ]; then
 	SWAPVOLSIZE=$(( SWAPSIZE / 1024 / 1024 ))
 
 	prepare_target "${TARGET}"
-	format_disk "${DISK}" "${PARTGRUB}" "${PARTBPOOL}" "${PARTRPOOL}" "${SWAPVOLSIZE}"
+	format_disk "${DISK}" "${PARTBASE}" "${PARTGRUB}" "${PARTBPOOL}" "${PARTRPOOL}" "${SWAPVOLSIZE}"
 	init_zfs "${TARGET}" "${DISK}${PARTBASE}${PARTBPOOL}" "${DISK}${PARTBASE}${PARTRPOOL}"
 	init_system_partitions "${TARGET}" "${DISK}${PARTBASE}1" "${DISK}${PARTBASE}${PARTGRUB}"
 
