also unmount the ESP if there is one

diff --git a/scripts/zsys-setup b/scripts/zsys-setup
--- a/scripts/zsys-setup
+++ b/scripts/zsys-setup
@@ -117,6 +117,7 @@ check_prerequisites() {
 
 prepare_target() {
 	target="$1"
+	esp="${target}/boot/efi"
 
 	if ! grep -qw "$target" /proc/mounts; then
 		echo "E: $target is not mounted. Exiting!"
@@ -136,21 +137,27 @@ prepare_target() {
 	# Give it some time and retry with a sleep between tries.
 	iter=0
 	maxiter=10
-	echo "I: umounting ${target}"
 
-	while :; do
-		# Do not make is quiet. We want to know why it failed.
-		if ! sudo umount "${target}"; then
-			iter=$(( iter + 1 ))
-			echo "W: Try ${iter}. Failed to umount ${target}."
-			if [ ${iter} -eq ${maxiter} ]; then
-				echo "E: Failed to umount ${target}. Exiting!"
-				exit 1
-			fi
-			sleep 3
-		else
-			break
+	for mountpoint in "${esp}" "${target}"; do
+		if [ ! -d "${mountpoint}" ]; then
+			continue
 		fi
+
+		echo "I: umounting ${mountpoint}"
+		while :; do
+			# Do not make it quiet. We want to know why it failed.
+			if ! sudo umount "${mountpoint}"; then
+				iter=$(( iter + 1 ))
+				echo "W: Try ${iter}. Failed to umount ${mountpoint}."
+				if [ ${iter} -eq ${maxiter} ]; then
+					echo "E: Failed to umount ${mountpoint}. Exiting!"
+					exit 1
+				fi
+				sleep 3
+			else
+				break
+			fi
+		done
 	done
 }
 
