zsys-setup: Quote variables where relevant

diff --git a/scripts/zsys-setup b/scripts/zsys-setup
--- a/scripts/zsys-setup
+++ b/scripts/zsys-setup
@@ -96,7 +96,7 @@ check_prerequisites() {
 }
 
 prepare_target() {
-	target=$1
+	target="$1"
 
 	if ! grep -qw "$target" /proc/mounts; then
 		echo "E: $target is not mounted. Exiting!"
@@ -106,32 +106,32 @@ prepare_target() {
 	# Save fstab generated by partman
 	if [ -f "$target/etc/fstab" ]; then
 	    echo "I: Saving existing fstab"
-		cp "$target/etc/fstab" /tmp/fstab.partman
+		cp "${target}/etc/fstab" /tmp/fstab.partman
 	else
-		echo "W: $target/etc/fstab doesn't exist"
+		echo "W: ${target}/etc/fstab doesn't exist"
 	fi
 
 	umount "$target" || true
 
 	if grep -qw "$target" /proc/mounts; then
-		echo "E: Failed to unmount $TARGET. Exiting!"
+		echo "E: Failed to unmount ${target}. Exiting!"
 		exit 1
 	fi
 }
 
 format_disk() {
-	disk=$1
-	partgrub=$2
-	partbpool=$3
-	partrpool=$4
+	disk="$1"
+	partgrub="$2"
+	partbpool="$3"
+	partrpool="$4"
 	partext=$(( $partgrub + 1 ))
 
-	echo "I: Formatting disk $disk with partitions grub:$partgrub ext:$partext bpool:$partbpool rpool:$partrpool"
+	echo "I: Formatting disk $disk with partitions grub:${partgrub} ext:${partext} bpool:${partbpool} rpool:${partrpool}"
 
 	start=$(sfdisk -l ${disk}|grep ^${disk}${partgrub}|awk '{print $2}')
 	# Partition hard drive
 	# TODO: retrieve start of sda1 or 2 and reuse it instead of 2048
-	sfdisk $disk<<EOF
+	sfdisk ${disk}<<EOF
 ${disk}${partgrub}  : start=        $start, size=    50M, type=83, bootable
 ${disk}${partext}   :                                   type=5
 ${disk}${partbpool} :                     size=     2G, type=a5
@@ -142,9 +142,9 @@ EOF
 }
 
 init_zfs() {
-	target=$1
-	partbpool=$2
-	partrpool=$3
+	target="$1"
+	partbpool="$2"
+	partrpool="$3"
 
 	echo "I: Initializing ZFS"
 	# Now we can create the pools and dataset
@@ -163,7 +163,7 @@ init_zfs() {
 		-O canmount=off \
 		-O dnodesize=auto \
 		-O sync=disabled \
-		-O mountpoint=/ -R $target rpool ${partrpool}
+		-O mountpoint=/ -R ${target} rpool ${partrpool}
 
 	# bpool
 	zpool create -f \
@@ -177,7 +177,7 @@ init_zfs() {
 		-O mountpoint=/ \
 		-O canmount=off \
 		-O devices=off \
-		-O mountpoint=/boot -R $target bpool ${partbpool}
+		-O mountpoint=/boot -R ${target} bpool ${partbpool}
 
 	# Root and boot dataset
 	zfs create rpool/ROOT -o canmount=off -o mountpoint=none
@@ -221,29 +221,29 @@ move_user () {
 	# $2 username
 	# $3 userhome
 	# $4 uuid
-	target=$1
-	user=$2
-	userhome=$3
-	uuid=$4
+	target="$1"
+	user="$2"
+	userhome="$3"
+	uuid="$4"
 
 	echo "I: Creating user $user with home $userhome"
-	mv $target/$userhome $target/tmp/home/$user
-	zfs create rpool/USERDATA/${user}_${uuid} -o canmount=on -o mountpoint=$userhome
-	chown $(chroot $target id -u $user):$(chroot $target id -g $user) $target/$userhome
-	rsync -a $target/tmp/home/$user/ $target/$userhome
-	bootfsdataset=$(grep "\s$target\s" /proc/mounts | awk '{ print $1 }')
-	zfs set org.zsys:bootfs-datasets=$bootfsdataset rpool/USERDATA/${user}_${UUID_ORIG}
+	mv ${target}/${userhome} ${target}/tmp/home/${user}
+	zfs create rpool/USERDATA/${user}_${uuid} -o canmount=on -o mountpoint=${userhome}
+	chown $(chroot ${target} id -u ${user}):$(chroot ${target} id -g ${user}) ${target}/${userhome}
+	rsync -a ${target}/tmp/home/${user}/ ${target}/${userhome}
+	bootfsdataset=$(grep "\s${target}\s" /proc/mounts | awk '{ print $1 }')
+	zfs set org.zsys:bootfs-datasets=${bootfsdataset} rpool/USERDATA/${user}_${UUID_ORIG}
 }
 
 init_grub() {
-	target=$1
-	partgrub=$2
+	target="$1"
+	partgrub="$2"
 
 	echo "I: Creating grub partition $partgrub"
 	# Finalize grub directory
-	mkdir -p $target/boot/grub
-	mke2fs -F -t ext4 $partgrub
-	mount -t ext4 $partgrub $target/boot/grub
+	mkdir -p ${target}/boot/grub
+	mke2fs -F -t ext4 ${partgrub}
+	mount -t ext4 ${partgrub} ${target}/boot/grub
 }
 
 check_prerequisites $REQUIREDPKGS
@@ -270,21 +270,21 @@ elif [ "$COMMAND" = "init" ]; then
 		swapoff $SWAPFILE
 	fi
 
-	prepare_target $TARGET
-	format_disk $DISK $PARTGRUB $PARTBPOOL $PARTRPOOL
-	init_zfs $TARGET ${DISK}${PARTBPOOL} ${DISK}${PARTRPOOL}
-	init_grub $TARGET ${DISK}${PARTGRUB}
+	prepare_target ${TARGET}
+	format_disk ${DISK} ${PARTGRUB} ${PARTBPOOL} ${PARTRPOOL}
+	init_zfs ${TARGET} ${DISK}${PARTBPOOL} ${DISK}${PARTRPOOL}
+	init_grub ${TARGET} ${DISK}${PARTGRUB}
 
 	# Generate fstab
 	# $TARGET/etc has been destroyed by the creation of the zfs partitition
 	# Recreate it
-	mkdir -p $TARGET/etc
+	mkdir -p ${TARGET}/etc
 	if [ -f /tmp/fstab.partman ]; then
 		echo "I: Creating fstab"
-		grep -Ev '\s/\s|/swapfile' /tmp/fstab.partman > "$TARGET/etc/fstab"
+		grep -Ev '\s/\s|/swapfile' /tmp/fstab.partman > "${TARGET}/etc/fstab"
 	fi
 	grubuuid=$(blkid -s UUID -o value ${DISK}${PARTGRUB})
-	echo "UUID=${grubuuid}\t/boot/grub\text4\terrors=remount-ro\t0\t1" >> "$TARGET/etc/fstab"
+	echo "UUID=${grubuuid}\t/boot/grub\text4\terrors=remount-ro\t0\t1" >> "${TARGET}/etc/fstab"
 
 	# Recreate swap file if there was one
 	if [ -n "$SWAPFILE" ]; then
@@ -297,7 +297,7 @@ elif [ "$COMMAND" = "init" ]; then
 			rpool/swap
 
 		mkswap -f /dev/zvol/rpool/swap
-		echo "/dev/zvol/rpool/swap\tnone\tswap\tdiscard\t0\t0" >> $TARGET/etc/fstab
+		echo "/dev/zvol/rpool/swap\tnone\tswap\tdiscard\t0\t0" >> ${TARGET}/etc/fstab
 		swapon -av
 	fi
 
@@ -307,33 +307,33 @@ elif [ "$COMMAND" = "finalize" ]; then
 	# The code below can be removed once zfs is seeded on desktop images
 	#
 	# We need network up at this point and resolv.conf
-	mount -o bind /dev $TARGET/dev
-	mount -o bind /proc $TARGET/proc
-	mount -o bind /run $TARGET/run
-	mount -o bind /sys $TARGET/sys
+	mount -o bind /dev ${TARGET}/dev
+	mount -o bind /proc ${TARGET}/proc
+	mount -o bind /run ${TARGET}/run
+	mount -o bind /sys ${TARGET}/sys
 	echo "I: Installing missing packages in $TARGET"
-	chroot $TARGET apt -qy install zfsutils-linux zfs-initramfs
-	umount $TARGET/dev || true
-	umount $TARGET/proc || true
-	umount $TARGET/run || true
-	umount $TARGET/sys || true
+	chroot ${TARGET} apt -qy install zfsutils-linux zfs-initramfs
+	umount ${TARGET}/dev || true
+	umount ${TARGET}/proc || true
+	umount ${TARGET}/run || true
+	umount ${TARGET}/sys || true
 
 	# Activate zfs generator.
 	# After enabling the generator we should run zfs set canmount=on DATASET
 	# in the chroot for one dataset of each pool to refresh the zfs cache.
 	echo "I: Activating zfs generator"
-	mkdir -p $TARGET/etc/zfs/zfs-list.cache
-	touch $TARGET/etc/zfs/zfs-list.cache/bpool $TARGET/etc/zfs/zfs-list.cache/rpool
-	ln -s /usr/lib/zfs-linux/zed.d/history_event-zfs-list-cacher.sh $TARGET/etc/zfs/zed.d
+	mkdir -p ${TARGET}/etc/zfs/zfs-list.cache
+	touch ${TARGET}/etc/zfs/zfs-list.cache/bpool ${TARGET}/etc/zfs/zfs-list.cache/rpool
+	ln -s /usr/lib/zfs-linux/zed.d/history_event-zfs-list-cacher.sh ${TARGET}/etc/zfs/zed.d
 
 	# Handle userdata
 	UUID_ORIG=$(head -100 /dev/urandom | tr -dc 'a-z0-9' |head -c6)
-	mkdir -p $TARGET/tmp/home
-	for user in $(ls $TARGET/home/); do
-		move_user $TARGET $user /home/$user $UUID_ORIG
+	mkdir -p ${TARGET}/tmp/home
+	for user in $(ls ${TARGET}/home/); do
+		move_user ${TARGET} ${user} /home/${user} ${UUID_ORIG}
 	done
 
-	move_user $TARGET root /root $UUID_ORIG
+	move_user ${TARGET} root /root ${UUID_ORIG}
 else
 	echo "E: Unknown command: $COMMAND"
 	exit 1
